/**
 * AUTO-GENERATED by scripts/generate-doctree.mjs — do not edit by hand.
 * A pruned snapshot of the real project tree used by the hidden /internal docs.
 * Regenerate with: npm run gen:doctree
 */
export interface TreeNode {
  name: string;
  path: string;
  type: "dir" | "file";
  children?: TreeNode[];
}

export const PROJECT_TREE: TreeNode[] = [
  {
    "name": "backend",
    "path": "backend",
    "type": "dir",
    "children": [
      {
        "name": "app",
        "path": "backend/app",
        "type": "dir",
        "children": [
          {
            "name": "api",
            "path": "backend/app/api",
            "type": "dir",
            "children": [
              {
                "name": "routers",
                "path": "backend/app/api/routers",
                "type": "dir",
                "children": [
                  {
                    "name": "__init__.py",
                    "path": "backend/app/api/routers/__init__.py",
                    "type": "file"
                  },
                  {
                    "name": "analytics.py",
                    "path": "backend/app/api/routers/analytics.py",
                    "type": "file"
                  },
                  {
                    "name": "health.py",
                    "path": "backend/app/api/routers/health.py",
                    "type": "file"
                  },
                  {
                    "name": "logs.py",
                    "path": "backend/app/api/routers/logs.py",
                    "type": "file"
                  },
                  {
                    "name": "models.py",
                    "path": "backend/app/api/routers/models.py",
                    "type": "file"
                  },
                  {
                    "name": "policies.py",
                    "path": "backend/app/api/routers/policies.py",
                    "type": "file"
                  },
                  {
                    "name": "services.py",
                    "path": "backend/app/api/routers/services.py",
                    "type": "file"
                  },
                  {
                    "name": "settings.py",
                    "path": "backend/app/api/routers/settings.py",
                    "type": "file"
                  },
                  {
                    "name": "simulation.py",
                    "path": "backend/app/api/routers/simulation.py",
                    "type": "file"
                  },
                  {
                    "name": "topology.py",
                    "path": "backend/app/api/routers/topology.py",
                    "type": "file"
                  },
                  {
                    "name": "twin.py",
                    "path": "backend/app/api/routers/twin.py",
                    "type": "file"
                  },
                  {
                    "name": "workflows.py",
                    "path": "backend/app/api/routers/workflows.py",
                    "type": "file"
                  },
                  {
                    "name": "ws.py",
                    "path": "backend/app/api/routers/ws.py",
                    "type": "file"
                  }
                ]
              },
              {
                "name": "schemas",
                "path": "backend/app/api/schemas",
                "type": "dir",
                "children": [
                  {
                    "name": "__init__.py",
                    "path": "backend/app/api/schemas/__init__.py",
                    "type": "file"
                  },
                  {
                    "name": "common.py",
                    "path": "backend/app/api/schemas/common.py",
                    "type": "file"
                  },
                  {
                    "name": "workflow.py",
                    "path": "backend/app/api/schemas/workflow.py",
                    "type": "file"
                  }
                ]
              },
              {
                "name": "ws",
                "path": "backend/app/api/ws",
                "type": "dir",
                "children": [
                  {
                    "name": "__init__.py",
                    "path": "backend/app/api/ws/__init__.py",
                    "type": "file"
                  },
                  {
                    "name": "hub.py",
                    "path": "backend/app/api/ws/hub.py",
                    "type": "file"
                  }
                ]
              },
              {
                "name": "__init__.py",
                "path": "backend/app/api/__init__.py",
                "type": "file"
              },
              {
                "name": "deps.py",
                "path": "backend/app/api/deps.py",
                "type": "file"
              },
              {
                "name": "errors.py",
                "path": "backend/app/api/errors.py",
                "type": "file"
              },
              {
                "name": "middleware.py",
                "path": "backend/app/api/middleware.py",
                "type": "file"
              }
            ]
          },
          {
            "name": "application",
            "path": "backend/app/application",
            "type": "dir",
            "children": [
              {
                "name": "agents",
                "path": "backend/app/application/agents",
                "type": "dir",
                "children": [
                  {
                    "name": "prompts",
                    "path": "backend/app/application/agents/prompts",
                    "type": "dir",
                    "children": [
                      {
                        "name": "exemplars",
                        "path": "backend/app/application/agents/prompts/exemplars",
                        "type": "dir",
                        "children": [
                          {
                            "name": "__init__.py",
                            "path": "backend/app/application/agents/prompts/exemplars/__init__.py",
                            "type": "file"
                          }
                        ]
                      },
                      {
                        "name": "__init__.py",
                        "path": "backend/app/application/agents/prompts/__init__.py",
                        "type": "file"
                      },
                      {
                        "name": "registry.py",
                        "path": "backend/app/application/agents/prompts/registry.py",
                        "type": "file"
                      }
                    ]
                  },
                  {
                    "name": "__init__.py",
                    "path": "backend/app/application/agents/__init__.py",
                    "type": "file"
                  },
                  {
                    "name": "base.py",
                    "path": "backend/app/application/agents/base.py",
                    "type": "file"
                  },
                  {
                    "name": "documentation.py",
                    "path": "backend/app/application/agents/documentation.py",
                    "type": "file"
                  },
                  {
                    "name": "executor.py",
                    "path": "backend/app/application/agents/executor.py",
                    "type": "file"
                  },
                  {
                    "name": "memory_agent.py",
                    "path": "backend/app/application/agents/memory_agent.py",
                    "type": "file"
                  },
                  {
                    "name": "observer.py",
                    "path": "backend/app/application/agents/observer.py",
                    "type": "file"
                  },
                  {
                    "name": "optimizer.py",
                    "path": "backend/app/application/agents/optimizer.py",
                    "type": "file"
                  },
                  {
                    "name": "orchestrator.py",
                    "path": "backend/app/application/agents/orchestrator.py",
                    "type": "file"
                  },
                  {
                    "name": "planner.py",
                    "path": "backend/app/application/agents/planner.py",
                    "type": "file"
                  },
                  {
                    "name": "recovery.py",
                    "path": "backend/app/application/agents/recovery.py",
                    "type": "file"
                  }
                ]
              },
              {
                "name": "recovery",
                "path": "backend/app/application/recovery",
                "type": "dir",
                "children": [
                  {
                    "name": "__init__.py",
                    "path": "backend/app/application/recovery/__init__.py",
                    "type": "file"
                  },
                  {
                    "name": "autonomous.py",
                    "path": "backend/app/application/recovery/autonomous.py",
                    "type": "file"
                  }
                ]
              },
              {
                "name": "sel",
                "path": "backend/app/application/sel",
                "type": "dir",
                "children": [
                  {
                    "name": "services",
                    "path": "backend/app/application/sel/services",
                    "type": "dir",
                    "children": [
                      {
                        "name": "__init__.py",
                        "path": "backend/app/application/sel/services/__init__.py",
                        "type": "file"
                      },
                      {
                        "name": "aimle.py",
                        "path": "backend/app/application/sel/services/aimle.py",
                        "type": "file"
                      },
                      {
                        "name": "catalog.py",
                        "path": "backend/app/application/sel/services/catalog.py",
                        "type": "file"
                      },
                      {
                        "name": "control_plane.py",
                        "path": "backend/app/application/sel/services/control_plane.py",
                        "type": "file"
                      },
                      {
                        "name": "dcf.py",
                        "path": "backend/app/application/sel/services/dcf.py",
                        "type": "file"
                      },
                      {
                        "name": "edge.py",
                        "path": "backend/app/application/sel/services/edge.py",
                        "type": "file"
                      },
                      {
                        "name": "mitigation.py",
                        "path": "backend/app/application/sel/services/mitigation.py",
                        "type": "file"
                      },
                      {
                        "name": "nrf.py",
                        "path": "backend/app/application/sel/services/nrf.py",
                        "type": "file"
                      },
                      {
                        "name": "nwdaf.py",
                        "path": "backend/app/application/sel/services/nwdaf.py",
                        "type": "file"
                      },
                      {
                        "name": "twin_read.py",
                        "path": "backend/app/application/sel/services/twin_read.py",
                        "type": "file"
                      },
                      {
                        "name": "upf.py",
                        "path": "backend/app/application/sel/services/upf.py",
                        "type": "file"
                      }
                    ]
                  },
                  {
                    "name": "__init__.py",
                    "path": "backend/app/application/sel/__init__.py",
                    "type": "file"
                  },
                  {
                    "name": "invoker.py",
                    "path": "backend/app/application/sel/invoker.py",
                    "type": "file"
                  },
                  {
                    "name": "policy_engine.py",
                    "path": "backend/app/application/sel/policy_engine.py",
                    "type": "file"
                  },
                  {
                    "name": "registry.py",
                    "path": "backend/app/application/sel/registry.py",
                    "type": "file"
                  },
                  {
                    "name": "tools.py",
                    "path": "backend/app/application/sel/tools.py",
                    "type": "file"
                  }
                ]
              },
              {
                "name": "twin_service",
                "path": "backend/app/application/twin_service",
                "type": "dir",
                "children": [
                  {
                    "name": "__init__.py",
                    "path": "backend/app/application/twin_service/__init__.py",
                    "type": "file"
                  },
                  {
                    "name": "scenarios.py",
                    "path": "backend/app/application/twin_service/scenarios.py",
                    "type": "file"
                  },
                  {
                    "name": "service.py",
                    "path": "backend/app/application/twin_service/service.py",
                    "type": "file"
                  }
                ]
              },
              {
                "name": "workflow",
                "path": "backend/app/application/workflow",
                "type": "dir",
                "children": [
                  {
                    "name": "__init__.py",
                    "path": "backend/app/application/workflow/__init__.py",
                    "type": "file"
                  },
                  {
                    "name": "engine.py",
                    "path": "backend/app/application/workflow/engine.py",
                    "type": "file"
                  },
                  {
                    "name": "nodes.py",
                    "path": "backend/app/application/workflow/nodes.py",
                    "type": "file"
                  },
                  {
                    "name": "routing.py",
                    "path": "backend/app/application/workflow/routing.py",
                    "type": "file"
                  },
                  {
                    "name": "state.py",
                    "path": "backend/app/application/workflow/state.py",
                    "type": "file"
                  },
                  {
                    "name": "triggers.py",
                    "path": "backend/app/application/workflow/triggers.py",
                    "type": "file"
                  }
                ]
              },
              {
                "name": "__init__.py",
                "path": "backend/app/application/__init__.py",
                "type": "file"
              }
            ]
          },
          {
            "name": "domain",
            "path": "backend/app/domain",
            "type": "dir",
            "children": [
              {
                "name": "agents",
                "path": "backend/app/domain/agents",
                "type": "dir",
                "children": [
                  {
                    "name": "__init__.py",
                    "path": "backend/app/domain/agents/__init__.py",
                    "type": "file"
                  },
                  {
                    "name": "memory.py",
                    "path": "backend/app/domain/agents/memory.py",
                    "type": "file"
                  },
                  {
                    "name": "models.py",
                    "path": "backend/app/domain/agents/models.py",
                    "type": "file"
                  },
                  {
                    "name": "ports.py",
                    "path": "backend/app/domain/agents/ports.py",
                    "type": "file"
                  }
                ]
              },
              {
                "name": "services",
                "path": "backend/app/domain/services",
                "type": "dir",
                "children": [
                  {
                    "name": "__init__.py",
                    "path": "backend/app/domain/services/__init__.py",
                    "type": "file"
                  },
                  {
                    "name": "models.py",
                    "path": "backend/app/domain/services/models.py",
                    "type": "file"
                  },
                  {
                    "name": "policy.py",
                    "path": "backend/app/domain/services/policy.py",
                    "type": "file"
                  },
                  {
                    "name": "ports.py",
                    "path": "backend/app/domain/services/ports.py",
                    "type": "file"
                  }
                ]
              },
              {
                "name": "twin",
                "path": "backend/app/domain/twin",
                "type": "dir",
                "children": [
                  {
                    "name": "nf",
                    "path": "backend/app/domain/twin/nf",
                    "type": "dir",
                    "children": [
                      {
                        "name": "__init__.py",
                        "path": "backend/app/domain/twin/nf/__init__.py",
                        "type": "file"
                      },
                      {
                        "name": "amf.py",
                        "path": "backend/app/domain/twin/nf/amf.py",
                        "type": "file"
                      },
                      {
                        "name": "dcf.py",
                        "path": "backend/app/domain/twin/nf/dcf.py",
                        "type": "file"
                      },
                      {
                        "name": "edge.py",
                        "path": "backend/app/domain/twin/nf/edge.py",
                        "type": "file"
                      },
                      {
                        "name": "nrf.py",
                        "path": "backend/app/domain/twin/nf/nrf.py",
                        "type": "file"
                      },
                      {
                        "name": "nwdaf.py",
                        "path": "backend/app/domain/twin/nf/nwdaf.py",
                        "type": "file"
                      },
                      {
                        "name": "remaining.py",
                        "path": "backend/app/domain/twin/nf/remaining.py",
                        "type": "file"
                      },
                      {
                        "name": "smf.py",
                        "path": "backend/app/domain/twin/nf/smf.py",
                        "type": "file"
                      },
                      {
                        "name": "upf.py",
                        "path": "backend/app/domain/twin/nf/upf.py",
                        "type": "file"
                      }
                    ]
                  },
                  {
                    "name": "__init__.py",
                    "path": "backend/app/domain/twin/__init__.py",
                    "type": "file"
                  },
                  {
                    "name": "entities.py",
                    "path": "backend/app/domain/twin/entities.py",
                    "type": "file"
                  },
                  {
                    "name": "events.py",
                    "path": "backend/app/domain/twin/events.py",
                    "type": "file"
                  },
                  {
                    "name": "kpi.py",
                    "path": "backend/app/domain/twin/kpi.py",
                    "type": "file"
                  },
                  {
                    "name": "network_twin.py",
                    "path": "backend/app/domain/twin/network_twin.py",
                    "type": "file"
                  },
                  {
                    "name": "ports.py",
                    "path": "backend/app/domain/twin/ports.py",
                    "type": "file"
                  },
                  {
                    "name": "profile.py",
                    "path": "backend/app/domain/twin/profile.py",
                    "type": "file"
                  },
                  {
                    "name": "topology.py",
                    "path": "backend/app/domain/twin/topology.py",
                    "type": "file"
                  }
                ]
              },
              {
                "name": "__init__.py",
                "path": "backend/app/domain/__init__.py",
                "type": "file"
              }
            ]
          },
          {
            "name": "infrastructure",
            "path": "backend/app/infrastructure",
            "type": "dir",
            "children": [
              {
                "name": "bus",
                "path": "backend/app/infrastructure/bus",
                "type": "dir",
                "children": [
                  {
                    "name": "__init__.py",
                    "path": "backend/app/infrastructure/bus/__init__.py",
                    "type": "file"
                  },
                  {
                    "name": "bus.py",
                    "path": "backend/app/infrastructure/bus/bus.py",
                    "type": "file"
                  }
                ]
              },
              {
                "name": "config",
                "path": "backend/app/infrastructure/config",
                "type": "dir",
                "children": [
                  {
                    "name": "__init__.py",
                    "path": "backend/app/infrastructure/config/__init__.py",
                    "type": "file"
                  },
                  {
                    "name": "settings.py",
                    "path": "backend/app/infrastructure/config/settings.py",
                    "type": "file"
                  }
                ]
              },
              {
                "name": "db",
                "path": "backend/app/infrastructure/db",
                "type": "dir",
                "children": [
                  {
                    "name": "repos",
                    "path": "backend/app/infrastructure/db/repos",
                    "type": "dir",
                    "children": [
                      {
                        "name": "__init__.py",
                        "path": "backend/app/infrastructure/db/repos/__init__.py",
                        "type": "file"
                      },
                      {
                        "name": "log_repo.py",
                        "path": "backend/app/infrastructure/db/repos/log_repo.py",
                        "type": "file"
                      },
                      {
                        "name": "memory_store.py",
                        "path": "backend/app/infrastructure/db/repos/memory_store.py",
                        "type": "file"
                      },
                      {
                        "name": "policy_store.py",
                        "path": "backend/app/infrastructure/db/repos/policy_store.py",
                        "type": "file"
                      },
                      {
                        "name": "workflow_repo.py",
                        "path": "backend/app/infrastructure/db/repos/workflow_repo.py",
                        "type": "file"
                      }
                    ]
                  },
                  {
                    "name": "__init__.py",
                    "path": "backend/app/infrastructure/db/__init__.py",
                    "type": "file"
                  },
                  {
                    "name": "engine.py",
                    "path": "backend/app/infrastructure/db/engine.py",
                    "type": "file"
                  },
                  {
                    "name": "models.py",
                    "path": "backend/app/infrastructure/db/models.py",
                    "type": "file"
                  },
                  {
                    "name": "seed.py",
                    "path": "backend/app/infrastructure/db/seed.py",
                    "type": "file"
                  }
                ]
              },
              {
                "name": "llm",
                "path": "backend/app/infrastructure/llm",
                "type": "dir",
                "children": [
                  {
                    "name": "__init__.py",
                    "path": "backend/app/infrastructure/llm/__init__.py",
                    "type": "file"
                  },
                  {
                    "name": "client.py",
                    "path": "backend/app/infrastructure/llm/client.py",
                    "type": "file"
                  }
                ]
              },
              {
                "name": "rng",
                "path": "backend/app/infrastructure/rng",
                "type": "dir",
                "children": [
                  {
                    "name": "__init__.py",
                    "path": "backend/app/infrastructure/rng/__init__.py",
                    "type": "file"
                  },
                  {
                    "name": "rng.py",
                    "path": "backend/app/infrastructure/rng/rng.py",
                    "type": "file"
                  }
                ]
              },
              {
                "name": "sim",
                "path": "backend/app/infrastructure/sim",
                "type": "dir",
                "children": [
                  {
                    "name": "__init__.py",
                    "path": "backend/app/infrastructure/sim/__init__.py",
                    "type": "file"
                  },
                  {
                    "name": "scheduler.py",
                    "path": "backend/app/infrastructure/sim/scheduler.py",
                    "type": "file"
                  }
                ]
              },
              {
                "name": "writer",
                "path": "backend/app/infrastructure/writer",
                "type": "dir",
                "children": [
                  {
                    "name": "__init__.py",
                    "path": "backend/app/infrastructure/writer/__init__.py",
                    "type": "file"
                  },
                  {
                    "name": "writer.py",
                    "path": "backend/app/infrastructure/writer/writer.py",
                    "type": "file"
                  }
                ]
              },
              {
                "name": "__init__.py",
                "path": "backend/app/infrastructure/__init__.py",
                "type": "file"
              },
              {
                "name": "container.py",
                "path": "backend/app/infrastructure/container.py",
                "type": "file"
              }
            ]
          },
          {
            "name": "__init__.py",
            "path": "backend/app/__init__.py",
            "type": "file"
          },
          {
            "name": "main.py",
            "path": "backend/app/main.py",
            "type": "file"
          }
        ]
      },
      {
        "name": "tests",
        "path": "backend/tests",
        "type": "dir",
        "children": [
          {
            "name": "determinism",
            "path": "backend/tests/determinism",
            "type": "dir",
            "children": [
              {
                "name": "__init__.py",
                "path": "backend/tests/determinism/__init__.py",
                "type": "file"
              },
              {
                "name": "test_golden_trajectory.py",
                "path": "backend/tests/determinism/test_golden_trajectory.py",
                "type": "file"
              },
              {
                "name": "test_golden_workflow.py",
                "path": "backend/tests/determinism/test_golden_workflow.py",
                "type": "file"
              }
            ]
          },
          {
            "name": "fixtures",
            "path": "backend/tests/fixtures",
            "type": "dir",
            "children": [
              {
                "name": "llm",
                "path": "backend/tests/fixtures/llm",
                "type": "dir",
                "children": [
                  {
                    "name": "__init__.py",
                    "path": "backend/tests/fixtures/llm/__init__.py",
                    "type": "file"
                  },
                  {
                    "name": "write_fixture.py",
                    "path": "backend/tests/fixtures/llm/write_fixture.py",
                    "type": "file"
                  }
                ]
              }
            ]
          },
          {
            "name": "integration",
            "path": "backend/tests/integration",
            "type": "dir",
            "children": [
              {
                "name": "__init__.py",
                "path": "backend/tests/integration/__init__.py",
                "type": "file"
              },
              {
                "name": "test_health.py",
                "path": "backend/tests/integration/test_health.py",
                "type": "file"
              },
              {
                "name": "test_scenario_a.py",
                "path": "backend/tests/integration/test_scenario_a.py",
                "type": "file"
              },
              {
                "name": "test_scenario_b.py",
                "path": "backend/tests/integration/test_scenario_b.py",
                "type": "file"
              },
              {
                "name": "test_scenario_c.py",
                "path": "backend/tests/integration/test_scenario_c.py",
                "type": "file"
              }
            ]
          },
          {
            "name": "safety",
            "path": "backend/tests/safety",
            "type": "dir",
            "children": [
              {
                "name": "__init__.py",
                "path": "backend/tests/safety/__init__.py",
                "type": "file"
              },
              {
                "name": "test_safety_invariants.py",
                "path": "backend/tests/safety/test_safety_invariants.py",
                "type": "file"
              }
            ]
          },
          {
            "name": "unit",
            "path": "backend/tests/unit",
            "type": "dir",
            "children": [
              {
                "name": "agents",
                "path": "backend/tests/unit/agents",
                "type": "dir",
                "children": [
                  {
                    "name": "__init__.py",
                    "path": "backend/tests/unit/agents/__init__.py",
                    "type": "file"
                  },
                  {
                    "name": "test_agent_models.py",
                    "path": "backend/tests/unit/agents/test_agent_models.py",
                    "type": "file"
                  },
                  {
                    "name": "test_ports.py",
                    "path": "backend/tests/unit/agents/test_ports.py",
                    "type": "file"
                  }
                ]
              },
              {
                "name": "api",
                "path": "backend/tests/unit/api",
                "type": "dir",
                "children": [
                  {
                    "name": "__init__.py",
                    "path": "backend/tests/unit/api/__init__.py",
                    "type": "file"
                  }
                ]
              },
              {
                "name": "infra",
                "path": "backend/tests/unit/infra",
                "type": "dir",
                "children": [
                  {
                    "name": "__init__.py",
                    "path": "backend/tests/unit/infra/__init__.py",
                    "type": "file"
                  },
                  {
                    "name": "test_bus_llm.py",
                    "path": "backend/tests/unit/infra/test_bus_llm.py",
                    "type": "file"
                  },
                  {
                    "name": "test_engine.py",
                    "path": "backend/tests/unit/infra/test_engine.py",
                    "type": "file"
                  },
                  {
                    "name": "test_orm_models.py",
                    "path": "backend/tests/unit/infra/test_orm_models.py",
                    "type": "file"
                  },
                  {
                    "name": "test_repos_seed_scheduler.py",
                    "path": "backend/tests/unit/infra/test_repos_seed_scheduler.py",
                    "type": "file"
                  },
                  {
                    "name": "test_rng.py",
                    "path": "backend/tests/unit/infra/test_rng.py",
                    "type": "file"
                  },
                  {
                    "name": "test_settings.py",
                    "path": "backend/tests/unit/infra/test_settings.py",
                    "type": "file"
                  },
                  {
                    "name": "test_writer.py",
                    "path": "backend/tests/unit/infra/test_writer.py",
                    "type": "file"
                  }
                ]
              },
              {
                "name": "sel",
                "path": "backend/tests/unit/sel",
                "type": "dir",
                "children": [
                  {
                    "name": "services",
                    "path": "backend/tests/unit/sel/services",
                    "type": "dir",
                    "children": [
                      {
                        "name": "__init__.py",
                        "path": "backend/tests/unit/sel/services/__init__.py",
                        "type": "file"
                      }
                    ]
                  },
                  {
                    "name": "__init__.py",
                    "path": "backend/tests/unit/sel/__init__.py",
                    "type": "file"
                  },
                  {
                    "name": "test_sel.py",
                    "path": "backend/tests/unit/sel/test_sel.py",
                    "type": "file"
                  }
                ]
              },
              {
                "name": "services",
                "path": "backend/tests/unit/services",
                "type": "dir",
                "children": [
                  {
                    "name": "__init__.py",
                    "path": "backend/tests/unit/services/__init__.py",
                    "type": "file"
                  },
                  {
                    "name": "test_service_models.py",
                    "path": "backend/tests/unit/services/test_service_models.py",
                    "type": "file"
                  }
                ]
              },
              {
                "name": "twin",
                "path": "backend/tests/unit/twin",
                "type": "dir",
                "children": [
                  {
                    "name": "__init__.py",
                    "path": "backend/tests/unit/twin/__init__.py",
                    "type": "file"
                  },
                  {
                    "name": "test_amf_smf_upf.py",
                    "path": "backend/tests/unit/twin/test_amf_smf_upf.py",
                    "type": "file"
                  },
                  {
                    "name": "test_entities_base.py",
                    "path": "backend/tests/unit/twin/test_entities_base.py",
                    "type": "file"
                  },
                  {
                    "name": "test_events.py",
                    "path": "backend/tests/unit/twin/test_events.py",
                    "type": "file"
                  },
                  {
                    "name": "test_kpi.py",
                    "path": "backend/tests/unit/twin/test_kpi.py",
                    "type": "file"
                  },
                  {
                    "name": "test_nrf.py",
                    "path": "backend/tests/unit/twin/test_nrf.py",
                    "type": "file"
                  },
                  {
                    "name": "test_profile.py",
                    "path": "backend/tests/unit/twin/test_profile.py",
                    "type": "file"
                  },
                  {
                    "name": "test_remaining_nfs.py",
                    "path": "backend/tests/unit/twin/test_remaining_nfs.py",
                    "type": "file"
                  },
                  {
                    "name": "test_topology.py",
                    "path": "backend/tests/unit/twin/test_topology.py",
                    "type": "file"
                  }
                ]
              },
              {
                "name": "__init__.py",
                "path": "backend/tests/unit/__init__.py",
                "type": "file"
              }
            ]
          },
          {
            "name": "__init__.py",
            "path": "backend/tests/__init__.py",
            "type": "file"
          }
        ]
      },
      {
        "name": ".env",
        "path": "backend/.env",
        "type": "file"
      },
      {
        "name": ".env.example",
        "path": "backend/.env.example",
        "type": "file"
      },
      {
        "name": "nixpacks.toml",
        "path": "backend/nixpacks.toml",
        "type": "file"
      },
      {
        "name": "pyproject.toml",
        "path": "backend/pyproject.toml",
        "type": "file"
      },
      {
        "name": "railway.json",
        "path": "backend/railway.json",
        "type": "file"
      }
    ]
  },
  {
    "name": "frontend",
    "path": "frontend",
    "type": "dir",
    "children": [
      {
        "name": "app",
        "path": "frontend/app",
        "type": "dir",
        "children": [
          {
            "name": "%5F%5Fpresent",
            "path": "frontend/app/%5F%5Fpresent",
            "type": "dir",
            "children": [
              {
                "name": "page.tsx",
                "path": "frontend/app/%5F%5Fpresent/page.tsx",
                "type": "file"
              }
            ]
          },
          {
            "name": "agent-console",
            "path": "frontend/app/agent-console",
            "type": "dir",
            "children": [
              {
                "name": "page.tsx",
                "path": "frontend/app/agent-console/page.tsx",
                "type": "file"
              }
            ]
          },
          {
            "name": "analytics",
            "path": "frontend/app/analytics",
            "type": "dir",
            "children": [
              {
                "name": "page.tsx",
                "path": "frontend/app/analytics/page.tsx",
                "type": "file"
              }
            ]
          },
          {
            "name": "dashboard",
            "path": "frontend/app/dashboard",
            "type": "dir",
            "children": [
              {
                "name": "page.tsx",
                "path": "frontend/app/dashboard/page.tsx",
                "type": "file"
              }
            ]
          },
          {
            "name": "digital-twin",
            "path": "frontend/app/digital-twin",
            "type": "dir",
            "children": [
              {
                "name": "page.tsx",
                "path": "frontend/app/digital-twin/page.tsx",
                "type": "file"
              }
            ]
          },
          {
            "name": "knowledge-graph",
            "path": "frontend/app/knowledge-graph",
            "type": "dir",
            "children": [
              {
                "name": "page.tsx",
                "path": "frontend/app/knowledge-graph/page.tsx",
                "type": "file"
              }
            ]
          },
          {
            "name": "logs",
            "path": "frontend/app/logs",
            "type": "dir",
            "children": [
              {
                "name": "page.tsx",
                "path": "frontend/app/logs/page.tsx",
                "type": "file"
              }
            ]
          },
          {
            "name": "memory",
            "path": "frontend/app/memory",
            "type": "dir",
            "children": [
              {
                "name": "page.tsx",
                "path": "frontend/app/memory/page.tsx",
                "type": "file"
              }
            ]
          },
          {
            "name": "model-manager",
            "path": "frontend/app/model-manager",
            "type": "dir",
            "children": [
              {
                "name": "page.tsx",
                "path": "frontend/app/model-manager/page.tsx",
                "type": "file"
              }
            ]
          },
          {
            "name": "service-registry",
            "path": "frontend/app/service-registry",
            "type": "dir",
            "children": [
              {
                "name": "page.tsx",
                "path": "frontend/app/service-registry/page.tsx",
                "type": "file"
              }
            ]
          },
          {
            "name": "settings",
            "path": "frontend/app/settings",
            "type": "dir",
            "children": [
              {
                "name": "page.tsx",
                "path": "frontend/app/settings/page.tsx",
                "type": "file"
              }
            ]
          },
          {
            "name": "simulation",
            "path": "frontend/app/simulation",
            "type": "dir",
            "children": [
              {
                "name": "page.tsx",
                "path": "frontend/app/simulation/page.tsx",
                "type": "file"
              }
            ]
          },
          {
            "name": "topology",
            "path": "frontend/app/topology",
            "type": "dir",
            "children": [
              {
                "name": "page.tsx",
                "path": "frontend/app/topology/page.tsx",
                "type": "file"
              }
            ]
          },
          {
            "name": "workflow-builder",
            "path": "frontend/app/workflow-builder",
            "type": "dir",
            "children": [
              {
                "name": "page.tsx",
                "path": "frontend/app/workflow-builder/page.tsx",
                "type": "file"
              }
            ]
          },
          {
            "name": "favicon.ico",
            "path": "frontend/app/favicon.ico",
            "type": "file"
          },
          {
            "name": "globals.css",
            "path": "frontend/app/globals.css",
            "type": "file"
          },
          {
            "name": "layout.tsx",
            "path": "frontend/app/layout.tsx",
            "type": "file"
          },
          {
            "name": "page.tsx",
            "path": "frontend/app/page.tsx",
            "type": "file"
          },
          {
            "name": "robots.ts",
            "path": "frontend/app/robots.ts",
            "type": "file"
          }
        ]
      },
      {
        "name": "components",
        "path": "frontend/components",
        "type": "dir",
        "children": [
          {
            "name": "presentation",
            "path": "frontend/components/presentation",
            "type": "dir",
            "children": [
              {
                "name": "slides",
                "path": "frontend/components/presentation/slides",
                "type": "dir",
                "children": [
                  {
                    "name": "ai-features-slide.tsx",
                    "path": "frontend/components/presentation/slides/ai-features-slide.tsx",
                    "type": "file"
                  },
                  {
                    "name": "architecture-slide.tsx",
                    "path": "frontend/components/presentation/slides/architecture-slide.tsx",
                    "type": "file"
                  },
                  {
                    "name": "demo-slide.tsx",
                    "path": "frontend/components/presentation/slides/demo-slide.tsx",
                    "type": "file"
                  },
                  {
                    "name": "features-slide.tsx",
                    "path": "frontend/components/presentation/slides/features-slide.tsx",
                    "type": "file"
                  },
                  {
                    "name": "future-slide.tsx",
                    "path": "frontend/components/presentation/slides/future-slide.tsx",
                    "type": "file"
                  },
                  {
                    "name": "problem-slide.tsx",
                    "path": "frontend/components/presentation/slides/problem-slide.tsx",
                    "type": "file"
                  },
                  {
                    "name": "solution-slide.tsx",
                    "path": "frontend/components/presentation/slides/solution-slide.tsx",
                    "type": "file"
                  },
                  {
                    "name": "team-slide.tsx",
                    "path": "frontend/components/presentation/slides/team-slide.tsx",
                    "type": "file"
                  },
                  {
                    "name": "tech-stack-slide.tsx",
                    "path": "frontend/components/presentation/slides/tech-stack-slide.tsx",
                    "type": "file"
                  },
                  {
                    "name": "thanks-slide.tsx",
                    "path": "frontend/components/presentation/slides/thanks-slide.tsx",
                    "type": "file"
                  },
                  {
                    "name": "welcome-slide.tsx",
                    "path": "frontend/components/presentation/slides/welcome-slide.tsx",
                    "type": "file"
                  },
                  {
                    "name": "workflow-slide.tsx",
                    "path": "frontend/components/presentation/slides/workflow-slide.tsx",
                    "type": "file"
                  }
                ]
              },
              {
                "name": "backgrounds.tsx",
                "path": "frontend/components/presentation/backgrounds.tsx",
                "type": "file"
              },
              {
                "name": "controls.tsx",
                "path": "frontend/components/presentation/controls.tsx",
                "type": "file"
              },
              {
                "name": "deck-stage.tsx",
                "path": "frontend/components/presentation/deck-stage.tsx",
                "type": "file"
              },
              {
                "name": "deck.tsx",
                "path": "frontend/components/presentation/deck.tsx",
                "type": "file"
              },
              {
                "name": "icons.tsx",
                "path": "frontend/components/presentation/icons.tsx",
                "type": "file"
              },
              {
                "name": "laser-pointer.tsx",
                "path": "frontend/components/presentation/laser-pointer.tsx",
                "type": "file"
              },
              {
                "name": "launch-screen.tsx",
                "path": "frontend/components/presentation/launch-screen.tsx",
                "type": "file"
              },
              {
                "name": "overview.tsx",
                "path": "frontend/components/presentation/overview.tsx",
                "type": "file"
              },
              {
                "name": "passphrase-gate.tsx",
                "path": "frontend/components/presentation/passphrase-gate.tsx",
                "type": "file"
              },
              {
                "name": "presentation-app.tsx",
                "path": "frontend/components/presentation/presentation-app.tsx",
                "type": "file"
              },
              {
                "name": "presenter-notes.tsx",
                "path": "frontend/components/presentation/presenter-notes.tsx",
                "type": "file"
              },
              {
                "name": "primitives.tsx",
                "path": "frontend/components/presentation/primitives.tsx",
                "type": "file"
              },
              {
                "name": "qr.tsx",
                "path": "frontend/components/presentation/qr.tsx",
                "type": "file"
              },
              {
                "name": "shortcuts-help.tsx",
                "path": "frontend/components/presentation/shortcuts-help.tsx",
                "type": "file"
              },
              {
                "name": "slide-registry.tsx",
                "path": "frontend/components/presentation/slide-registry.tsx",
                "type": "file"
              }
            ]
          },
          {
            "name": "shell",
            "path": "frontend/components/shell",
            "type": "dir",
            "children": [
              {
                "name": "nav-rail.tsx",
                "path": "frontend/components/shell/nav-rail.tsx",
                "type": "file"
              },
              {
                "name": "top-bar.tsx",
                "path": "frontend/components/shell/top-bar.tsx",
                "type": "file"
              }
            ]
          },
          {
            "name": "states",
            "path": "frontend/components/states",
            "type": "dir",
            "children": [
              {
                "name": "empty-state.tsx",
                "path": "frontend/components/states/empty-state.tsx",
                "type": "file"
              },
              {
                "name": "error-state.tsx",
                "path": "frontend/components/states/error-state.tsx",
                "type": "file"
              },
              {
                "name": "skeleton.tsx",
                "path": "frontend/components/states/skeleton.tsx",
                "type": "file"
              }
            ]
          },
          {
            "name": "error-boundary.tsx",
            "path": "frontend/components/error-boundary.tsx",
            "type": "file"
          },
          {
            "name": "event-feed.tsx",
            "path": "frontend/components/event-feed.tsx",
            "type": "file"
          },
          {
            "name": "panel.tsx",
            "path": "frontend/components/panel.tsx",
            "type": "file"
          },
          {
            "name": "providers.tsx",
            "path": "frontend/components/providers.tsx",
            "type": "file"
          },
          {
            "name": "secret-hotkey.tsx",
            "path": "frontend/components/secret-hotkey.tsx",
            "type": "file"
          },
          {
            "name": "section-title.tsx",
            "path": "frontend/components/section-title.tsx",
            "type": "file"
          },
          {
            "name": "splash-screen.tsx",
            "path": "frontend/components/splash-screen.tsx",
            "type": "file"
          },
          {
            "name": "stat-card.tsx",
            "path": "frontend/components/stat-card.tsx",
            "type": "file"
          },
          {
            "name": "status-badge.tsx",
            "path": "frontend/components/status-badge.tsx",
            "type": "file"
          },
          {
            "name": "timeline-stepper.tsx",
            "path": "frontend/components/timeline-stepper.tsx",
            "type": "file"
          }
        ]
      },
      {
        "name": "e2e",
        "path": "frontend/e2e",
        "type": "dir",
        "children": [
          {
            "name": "scenario-a.spec.ts",
            "path": "frontend/e2e/scenario-a.spec.ts",
            "type": "file"
          },
          {
            "name": "scenario-b.spec.ts",
            "path": "frontend/e2e/scenario-b.spec.ts",
            "type": "file"
          },
          {
            "name": "scenario-c.spec.ts",
            "path": "frontend/e2e/scenario-c.spec.ts",
            "type": "file"
          }
        ]
      },
      {
        "name": "lib",
        "path": "frontend/lib",
        "type": "dir",
        "children": [
          {
            "name": "api",
            "path": "frontend/lib/api",
            "type": "dir",
            "children": [
              {
                "name": "client.ts",
                "path": "frontend/lib/api/client.ts",
                "type": "file"
              },
              {
                "name": "types.gen.ts",
                "path": "frontend/lib/api/types.gen.ts",
                "type": "file"
              }
            ]
          },
          {
            "name": "presentation",
            "path": "frontend/lib/presentation",
            "type": "dir",
            "children": [
              {
                "name": "confetti.ts",
                "path": "frontend/lib/presentation/confetti.ts",
                "type": "file"
              },
              {
                "name": "config.ts",
                "path": "frontend/lib/presentation/config.ts",
                "type": "file"
              },
              {
                "name": "deck-context.tsx",
                "path": "frontend/lib/presentation/deck-context.tsx",
                "type": "file"
              },
              {
                "name": "motion.ts",
                "path": "frontend/lib/presentation/motion.ts",
                "type": "file"
              },
              {
                "name": "use-fullscreen.ts",
                "path": "frontend/lib/presentation/use-fullscreen.ts",
                "type": "file"
              },
              {
                "name": "use-idle-cursor.ts",
                "path": "frontend/lib/presentation/use-idle-cursor.ts",
                "type": "file"
              }
            ]
          },
          {
            "name": "query",
            "path": "frontend/lib/query",
            "type": "dir",
            "children": [
              {
                "name": "client.ts",
                "path": "frontend/lib/query/client.ts",
                "type": "file"
              },
              {
                "name": "keys.ts",
                "path": "frontend/lib/query/keys.ts",
                "type": "file"
              }
            ]
          },
          {
            "name": "ws",
            "path": "frontend/lib/ws",
            "type": "dir",
            "children": [
              {
                "name": "store.ts",
                "path": "frontend/lib/ws/store.ts",
                "type": "file"
              },
              {
                "name": "ws-init.tsx",
                "path": "frontend/lib/ws/ws-init.tsx",
                "type": "file"
              }
            ]
          }
        ]
      },
      {
        "name": "public",
        "path": "frontend/public",
        "type": "dir",
        "children": [
          {
            "name": "agent5g-brochure.pdf",
            "path": "frontend/public/agent5g-brochure.pdf",
            "type": "file"
          }
        ]
      },
      {
        "name": "scripts",
        "path": "frontend/scripts",
        "type": "dir",
        "children": [
          {
            "name": "generate-brochure.mjs",
            "path": "frontend/scripts/generate-brochure.mjs",
            "type": "file"
          },
          {
            "name": "generate-doctree.mjs",
            "path": "frontend/scripts/generate-doctree.mjs",
            "type": "file"
          }
        ]
      },
      {
        "name": "test",
        "path": "frontend/test",
        "type": "dir",
        "children": [
          {
            "name": "components.test.tsx",
            "path": "frontend/test/components.test.tsx",
            "type": "file"
          },
          {
            "name": "setup.ts",
            "path": "frontend/test/setup.ts",
            "type": "file"
          },
          {
            "name": "ws-store.test.ts",
            "path": "frontend/test/ws-store.test.ts",
            "type": "file"
          }
        ]
      },
      {
        "name": ".env.local",
        "path": "frontend/.env.local",
        "type": "file"
      },
      {
        "name": ".env.local.example",
        "path": "frontend/.env.local.example",
        "type": "file"
      },
      {
        "name": ".gitignore",
        "path": "frontend/.gitignore",
        "type": "file"
      },
      {
        "name": ".node-version",
        "path": "frontend/.node-version",
        "type": "file"
      },
      {
        "name": ".prettierignore",
        "path": "frontend/.prettierignore",
        "type": "file"
      },
      {
        "name": ".prettierrc",
        "path": "frontend/.prettierrc",
        "type": "file"
      },
      {
        "name": "AGENTS.md",
        "path": "frontend/AGENTS.md",
        "type": "file"
      },
      {
        "name": "CLAUDE.md",
        "path": "frontend/CLAUDE.md",
        "type": "file"
      },
      {
        "name": "eslint.config.mjs",
        "path": "frontend/eslint.config.mjs",
        "type": "file"
      },
      {
        "name": "next-env.d.ts",
        "path": "frontend/next-env.d.ts",
        "type": "file"
      },
      {
        "name": "next.config.ts",
        "path": "frontend/next.config.ts",
        "type": "file"
      },
      {
        "name": "nixpacks.toml",
        "path": "frontend/nixpacks.toml",
        "type": "file"
      },
      {
        "name": "package-lock.json",
        "path": "frontend/package-lock.json",
        "type": "file"
      },
      {
        "name": "package.json",
        "path": "frontend/package.json",
        "type": "file"
      },
      {
        "name": "playwright.config.ts",
        "path": "frontend/playwright.config.ts",
        "type": "file"
      },
      {
        "name": "postcss.config.mjs",
        "path": "frontend/postcss.config.mjs",
        "type": "file"
      },
      {
        "name": "railway.json",
        "path": "frontend/railway.json",
        "type": "file"
      },
      {
        "name": "README.md",
        "path": "frontend/README.md",
        "type": "file"
      },
      {
        "name": "tsconfig.json",
        "path": "frontend/tsconfig.json",
        "type": "file"
      },
      {
        "name": "vitest.config.ts",
        "path": "frontend/vitest.config.ts",
        "type": "file"
      }
    ]
  }
];

export const PROJECT_TREE_FILE_COUNT = 261;
