/**
 * Generates a pruned snapshot of the real project tree (backend + frontend)
 * for the hidden /internal documentation page.
 *
 * Walks the workspace root (one level above frontend/), skips heavy/generated
 * folders, and writes a typed tree to frontend/lib/docs/project-tree.ts.
 *
 * Re-run any time the structure changes: `npm run gen:doctree`.
 */
import { readdirSync, statSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..", ".."); // workspace root (contains backend/ + frontend/)
const OUT = join(__dirname, "..", "lib", "docs", "project-tree.ts");

const SKIP_DIRS = new Set([
  "node_modules", ".next", ".git", ".venv", "venv", "__pycache__",
  ".mypy_cache", ".ruff_cache", ".pytest_cache", ".import_linter_cache",
  ".agents", ".turbo", ".idea", ".vscode", "coverage", "playwright-report",
  "test-results", "dist", "build", ".cache", "data",
]);
const SKIP_FILE_RE = /\.(pyc|tsbuildinfo|log|db|db-wal|db-shm)$|^\.DS_Store$/;
const SKIP_DIR_SUFFIX = [".egg-info"];
const MAX_DEPTH = 6;
const MAX_CHILDREN = 60;

function skipDir(name) {
  if (SKIP_DIRS.has(name)) return true;
  if (name.startsWith(".") && name !== ".github") return true;
  return SKIP_DIR_SUFFIX.some((s) => name.endsWith(s));
}

function walk(abs, depth) {
  let entries;
  try {
    entries = readdirSync(abs);
  } catch {
    return [];
  }
  const dirs = [];
  const files = [];
  for (const name of entries) {
    const full = join(abs, name);
    let st;
    try {
      st = statSync(full);
    } catch {
      continue;
    }
    if (st.isDirectory()) {
      if (skipDir(name)) continue;
      dirs.push(name);
    } else {
      if (SKIP_FILE_RE.test(name)) continue;
      files.push(name);
    }
  }
  dirs.sort((a, b) => a.localeCompare(b));
  files.sort((a, b) => a.localeCompare(b));

  const nodes = [];
  for (const name of dirs) {
    const full = join(abs, name);
    const rel = relative(ROOT, full).split(sep).join("/");
    const node = { name, path: rel, type: "dir", children: [] };
    if (depth < MAX_DEPTH) node.children = walk(full, depth + 1).slice(0, MAX_CHILDREN);
    nodes.push(node);
  }
  for (const name of files) {
    const rel = relative(ROOT, join(abs, name)).split(sep).join("/");
    nodes.push({ name, path: rel, type: "file" });
  }
  return nodes;
}

// Build only the two app roots we care about (keeps the tree focused + small).
const roots = ["backend", "frontend"].map((r) => {
  const abs = join(ROOT, r);
  return { name: r, path: r, type: "dir", children: walk(abs, 1).slice(0, MAX_CHILDREN) };
});

function countFiles(node) {
  if (node.type === "file") return 1;
  return (node.children ?? []).reduce((n, c) => n + countFiles(c), 0);
}
const total = roots.reduce((n, r) => n + countFiles(r), 0);

const banner = `/**
 * AUTO-GENERATED by scripts/generate-doctree.mjs — do not edit by hand.
 * A pruned snapshot of the real project tree used by the hidden /internal docs.
 * Regenerate with: npm run gen:doctree
 */
export interface TreeNode {
  name: string;
  path: string;
  type: "dir" | "file";
  children?: TreeNode[];
}

`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(
  OUT,
  banner +
    `export const PROJECT_TREE: TreeNode[] = ${JSON.stringify(roots, null, 2)};\n\n` +
    `export const PROJECT_TREE_FILE_COUNT = ${total};\n`,
);

console.log(`Doc tree written: ${OUT} (${total} files across ${roots.length} roots)`);
